### ISSUE TITLE
Multi selection & Lasso

### ISSUE THREAD

**Issue by lee-orr** [brendanjmeade/celeri_ui#1]

**Comment by jploveless** [comment]
This is really nice! 

I do think that having the ability to select multiple _segments_ would be really nice, so that we could change the properties for a whole set of segments at once (for example, apply a new locking depth or dip to a series of segments). 

I also think it would be nice to be able to delete segments. I know this is possible using the "merge" tool in the vertices panel, but from a workflow perspective, it is often helpful to be able to delete a bunch of segments at once. In our old code, we used a hidden plotting of the mid-point of each segment as the basis for selecting (i.e. draw a box, and whichever segment mid-points are in that box would be selected/deleted). 

Having a lasso selection would also be really nice, because more often than not, we want to select/delete a set of segments that follow a complicated geometry that doesn't neatly fit into a single box.

**Comment by lee-orr** [comment]
Thanks for the details! I'm going to re-open the issue, and re-add it to the queue. Some aspects of this will require abit more thought/planning, so the improvements might not be the very next thing I do, but I'll get to them soon.

**Comment by lee-orr** [comment]
@brendanjmeade @jploveless @Emilycm-97 - please test out the new lasso tool (by clicking the button in the panel on the bottom left) and let me know what you think.

**Comment by lee-orr** [comment]
I'll adjust the text to clarify it - click on points to create a polygon outlining the area you want to select (it'll show a white polygon overlaying the area), then click enter

**Comment by brendanjmeade** [comment]
Ok, I'm making some progress!  I can click around and select the vertices in a polygon.  See screenshot below.  How do I delete or modify segment properties associated with these?  Is that coming next?


<img width="555" alt="Screen Shot 2022-05-10 at 12 59 10 PM" src="https://user-images.githubusercontent.com/4225359/167682995-f634308f-7659-468d-8eb2-c104425fe804.png">

**Comment by lee-orr** [comment]
You should see the selected elements in the panel on the right hand side. You do need to make sure you are in the right mode for the element you care about - i.e. Segment mode for editing segments, vertex mode for editing vertices, etc.

**Comment by brendanjmeade** [comment]
I've been trying this a bit more.  The polygon selection is working OK though it seems to always have a small vertical segment at the top (see previous screenshot and the one attached here).  With the example attached here, I've selected multiple segments(?) with a polygon but I can't see what to click on to delete them or modify properties.  I think perhaps a quick Zoom about this might be the fastest way for me to learn.  Is there a time that might work well for you?

<img width="1727" alt="Screen Shot 2022-05-10 at 10 01 33 PM" src="https://user-images.githubusercontent.com/4225359/167754401-01a753e1-374c-4526-83bc-d63b76067a73.png">
