### ISSUE TITLE
Plot fault dips

### ISSUE THREAD

**Issue by lee-orr** [brendanjmeade/celeri_ui#9]
Plot fault dips.  These are rectangles that show the surface projection of the three-dimensional fault geometry for rectangular fault segments that have a dip other than 90 degrees and a locking depth greater than zero.  We have Matlab code that shows exactly how to do this: https://github.com/jploveless/Blocks/blob/master/SegmentManager/PlotDips.m.

**Comment by lee-orr** [comment]
@brendanjmeade @jploveless - I'm not familiar enough with matlab & some of the concepts here to fully parse the code. I implemented an initial version based on my best guess, but it would be great if one of you could verify if it's accurate, and if not find a time to meet and go over the actual expectations so that I can implement it properly?
You should be able to test it in the map, and the code for the projection function I wrote is located here: https://github.com/brendanjmeade/celeri_ui/blob/dfd39546801e8a0933de4decb0b496420ed24d8a/src/State/Segment/State.ts#L53

**Comment by jploveless** [comment]
Lee-Orr, this looks great overall! In checking out some details, some faults seem to be different from the convention we have used in the past, which is that, when looking from the west endpoint to the east endpoint, a dip < 90º indicates dipping to the right, and a dip > 90º indicates dipping to the left. 

I'm attaching a small screenshot from our Matlab equivalent of the UI that illustrates this. Red polygons are the fault projections, and the numbers indicate dip. All of these segments dip to the east, and all but 1 has a dip < 90º. The only segment whose dip is 120º is that whose western endpoint is also the northern endpoint. So, when looking from west to east along this segment, we need to specify its dip as 120º in order to have it dip 60º to the east, like the neighboring segments. 
<img width="400" alt="Screen Shot 2022-03-28 at 8 07 59 PM" src="https://user-images.githubusercontent.com/7537266/160507847-25759f14-0315-4999-8272-41dff4b9d24e.png">


It seems like in this same region, the convention used in `projectSegment()` is opposite of that we have used in the past. One of our first steps in our codes is to sort each segment's endpoints, so that the western is called the start and the eastern is called the end, and I wonder if something similar here could address the dips.

**Comment by brendanjmeade** [comment]
@lee-orr This is really close and really great.  @jploveless is exactly right.  I'm sharing a screenshot similar to that above that shows the anomalous segment.  I'm betting that Jack's initial vertex sorting solution will solve this, and that's a step we always take.  Getting there!

<img width="456" alt="Screen Shot 2022-03-28 at 11 52 26 PM" src="https://user-images.githubusercontent.com/4225359/160530329-7af0b072-ff92-4e8a-9072-b454342eb8f9.png">

**Comment by lee-orr** [comment]
Thanks! I was missing the understanding of how the dip was interpreted - a new build is publishing now.

**Comment by jploveless** [comment]
Looks great! I checked the example area I had posted yesterday, and the dip projections are correct. Thanks!

**Comment by brendanjmeade** [comment]
Thanks @lee-orr and @jploveless!
